---
title: "TA Hours 2022"
author: "steppe"
date: "2/16/2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

R for data science,  2022 edition.  Why they so mean to us? I do not know, but I expect they know this is the hardest class to TA...
  
```{r, warning = F, message = F, echo = F}
library(tidyverse)
library(calendR)
```


```{r Lab lengths, echo = F, results = 'hide'}
lab_l_min <- 110
labs <- data.frame(
  week = rep(3:9, each = 2), 
  dow = 'Friday',
  session = rep(c('A','B'), length(3:9)), 
  minutes = lab_l_min, 
  activity = 'Lab'
  ) 

sum(labs$minutes)/60 # 26 hours in labs

rm(lab_l_min)
```

```{r Lecture Lengths, echo = F, results = 'hide'}
lecture_l_min <- 80

lectures <- data.frame(
  week = rep(3:9, each = 2),
  dow = rep(c('Tuesday','Thursday'), length(3:9)), 
  session = NA,
  minutes = lecture_l_min, 
  activity = 'Lecture'
  )

sum(lectures$minutes)/60

rm(lecture_l_min)
```


```{r TA Hours, echo = F, results = 'hide'}
ta_l_min <-60

ta <- data.frame(
  week = c(rep(2:9, each = 2), 10),
  dow = c(rep(c('Monday','Wednesday'), length(2:9)), 'Wednesday'),
  session = NA, 
  minutes = ta_l_min,
  activity = 'Office_Hour'
  )

rm(ta_l_min)
```

```{r Requested TA Hours, echo = F, results = 'hide'}
ta_r <- data.frame(
  week = c(4, 5, 8),
  dow = c("Wednesday", "Wednesday","Wednesday"),
  session = NA, 
  minutes = c(20, 20, 25),
  activity = rep('Office Hour', times = 3)
  )

ta <- rbind(ta, ta_r) 

rm(ta_r)
```


```{r Grading hours, echo = F, results = 'hide'}
grading = data.frame(
  week = c(4,5,5,6,8,11,11),
  dow = c(rep('Sunday', 5), 'Wednesday','Friday'),
  session = NA, 
  minutes = c(120, 90, 90, 135, 120, 240, 420),
  activity = 'Grading'
)

sum(grading$minutes)/60
  
```


```{r develop lecture, echo = F}
lecture_prep <- data.frame(
  week = c(3,4,5),
  dow = 'Saturday',
  session = NA, 
  minutes = c(360, 420, 420),
  activity = 'Lecture_prep'
)
```

```{r Look up table, echo = F, results = 'hide'}

day <- c(1:31, 1:28, 1:31)
month <- c(rep(01, times = 31), rep(02, times = 28), rep(03,  times = 31))
weekday_vector <- c('Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') 
dow <- c(weekday_vector[7], rep(weekday_vector, times = ceiling((length(day) - 1)/ length(weekday_vector))))
week <- c(0, rep(1:13, each = 7))

lapply(list(day, month, dow, week),  FUN = length)
dow <- dow[1:90]
week <- week[1:90]

lookup_table <- data.frame(month, day, dow, week)

rm(day, month, weekday_vector, dow, week)
```


```{r, echo = F, message = F}
structured_hours <- rbind(labs, lectures, ta, grading, lecture_prep) %>% 
  mutate(year =2022) %>% 
  mutate(month = case_when(
    week %in% 1:4 ~ 01,
    week %in% 5 & dow %in% c('Sunday', 'Monday') ~ 01,
    week %in% 5:8 ~ 02, 
    week %in% 9 & dow %in% c('Sunday', 'Monday') ~ 02,
    week %in% 9:11 ~ 03,
  )) # actually unnecessary
  
hours <- left_join(structured_hours, lookup_table, by = c('month', 'week', 'dow')) %>% 
  unite('Date', year:day, sep = '-', remove = F) %>% 
  mutate(Date = as.Date(Date, "%Y-%m-%d"))

rm(labs, lectures, ta, grading, lecture_prep)
```

```{r Activity Calendar, echo = F, message=F}

hours_jan <- hours %>% filter(month == 1) %>% arrange(Date)
events_jan <- seq(as.Date("2022-01-01"), as.Date("2022-01-31"), by = "1 day")
events_jan <- ifelse(events_jan %in% events_jan[c(hours_jan$day)], 'A', NA)
events_jan[c(hours_jan$day)] <- sub("_", " ", hours_jan$activity )

colors <- c('cadetblue1', 'slateblue1', 'coral1', 'lightpink1', 'lightgreen')

jan <- calendR(year = 2022, month = 1,
        title = 'January',
        special.days = events_jan,
        special.col = colors,
        low.col = "white",
        legend.pos = "none", # Legend position
        legend.title = "Activity:", 
        weeknames = c("Mo", "Tu", "We", "Th", "Fr", "Sa","Su"), 
        title.col = "black"
        ) 

hours_feb <- hours %>% filter(month == 2) %>% arrange(Date)
events_feb <- seq(as.Date("2022-02-01"), as.Date("2022-02-28"), by = "1 day")
events_feb <- ifelse(events_feb %in% events_feb[c(hours_feb$day)], 'A', NA)
events_feb[c(hours_feb$day)] <- sub("_", " ", hours_feb$activity)

feb <- calendR(year = 2022, month = 2,
        title = 'February',
        special.days = events_feb,
        special.col = colors,
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "Activity:", # legend title
        weeknames = c("Mo", "Tu", "We", "Th", "Fr", "Sa","Su") ,
        title.col = "black"
        )   

hours_mar <- hours %>% filter(month == 3) %>% arrange(Date)
events_mar <- seq(as.Date("2022-03-01"), as.Date("2022-03-31"), by = "1 day")
events_mar <- ifelse(events_mar %in% events_mar[c(hours_mar$day)], 'A', NA)
events_mar[c(hours_mar$day)] <- sub("_", " ", hours_mar$activity)

mar <- calendR(year = 2022, month = 3,
        title = 'March',
        special.days = events_mar,
        special.col = colors[c(1:3,5)], # as events
        low.col = "white",
        legend.pos = "none", # Legend position
        legend.title = "Activity",
        weeknames = c("Mo", "Tu", "We", "Th", "Fr", "Sa","Su"),
        title.col = "black"
        ) 

calendar <- cowplot::plot_grid(jan, feb, mar, ncol = 3)
calendar
cowplot::save_plot(calendar, filename = 'TA_hours_2022.png', ncol = 3)
rm(hours_jan, hours_feb, hours_mar, events_jan, events_feb, events_mar, jan, mar, feb, calendar, colors)
```

```{r Hours by Day}

Day_hour_activity <- hours %>% 
  mutate(Hours = minutes/60) %>% 
  mutate(Hours = plyr::round_any(minutes, 15, ceiling)) %>% 
  mutate(Hours = Hours/60) %>% 
  select(Date, Hours, Activity = activity) %>% 
  arrange(Date)

Day_hour_activity_raw <- hours %>% 
  mutate(Hours = minutes/60) %>% 
  #summarize(n = sum(Hours)) %>% 
  mutate(Hours = format(round(Hours, 2), nsmall = 2)) %>% 
  select(Date, Hours, Activity = activity)%>% 
  arrange(Date)

write.csv(Day_hour_activity, 'hrs_by_date__rounded.csv')
write.csv(Day_hour_activity_raw, 'hrs_by_date_raw.csv')

rm(Day_hour_activity, Day_hour_activity_raw)
```

```{r Hours by Pay Period}

pp1 = as.Date(c('2022-01-09', '2022-01-22'), "%Y-%m-%d")
pp2 = as.Date(c('2022-01-23', '2022-02-05'), "%Y-%m-%d")
pp3 = as.Date(c('2022-02-06', '2022-02-19'), "%Y-%m-%d")
pp4 = as.Date(c('2022-02-20', '2022-03-05'), "%Y-%m-%d")
pp5 = as.Date(c('2022-03-06', '2022-03-19'), "%Y-%m-%d") 

hours_biweekly <- hours %>% 
  mutate(Pay_Period = case_when(
    Date >= pp1[1] & Date <= pp1[2]~ 1,
    Date >= pp2[1] & Date <= pp2[2]~ 2,
    Date >= pp3[1] & Date <= pp3[2]~ 3,
    Date >= pp4[1] & Date <= pp4[2]~ 4,
    Date >= pp5[1] & Date <= pp5[2]~ 5
    )
  )

total_biweekly_hours <- hours_biweekly %>%
  group_by(Pay_Period) %>% 
  summarise(Total_Hours = sum(minutes)/60) %>% 
  mutate(Total_Hours = format(round(Total_Hours, 2), nsmall = 2)) %>% 
  arrange(Pay_Period)

biweekly_hours_by_activity  <- hours_biweekly %>% 
  group_by(Pay_Period, activity) %>% 
  summarise(Weekly_Hours_Activity = sum(minutes)/60) %>% 
  mutate(Weekly_Hours_Activity = format(round(Weekly_Hours_Activity, 2), nsmall = 2)) %>% 
  arrange(Pay_Period)

write.csv(total_biweekly_hours, 'hrs_by_payperiod.csv')
write.csv(biweekly_hours_by_activity, 'hrs_by_payperiod_by_activity.csv')

rm(pp1, pp2, pp3, pp4, pp5, hours_biweekly, total_biweekly_hours, biweekly_hours_by_activity)
```



```{r, echo = F, message =F}

hours <- left_join(lookup_table, structured_hours, by = c('month', 'week', 'dow')) %>% 
  unite('Date', year:day, sep = '-', remove = F) %>% 
  mutate(Date = as.Date(Date, "%Y-%m-%d")) %>% 
  group_by(month, day) %>% 
  summarise(m_total = sum(minutes)) %>% 
  mutate(m_total = replace_na(m_total, 0)) %>% 
  mutate(m_total = m_total/60) %>% 
  pull(m_total)
  
calendR(start_date = "2022-01-01", # Custom start date
        end_date = "2022-03-31",
        weeknames = c("Mo", "Tu", "We", "Th", "Fr", "Sa","Su"),
        special.days = hours,
        
        # add a legend and modify it's display settings here
        gradient = TRUE,           # Set gradient = TRUE to create the heatmap
        special.col = "deeppink4", # Color of the gradient for the highest value
        low.col = "gray98",
        legend.pos = "bottom",     # Position of the legend
        legend.title = "Hours",
        
        # add title and subtitle and style them here. 
        title = "TA Hours - R for Data Science 2022",
        title.col = "black",
        
        subtitle = "PBC 470 / ENVR SCI 390 / EARTH 390",
        subtitle.col = "black"
       # ,
      #  pdf = TRUE,
      #  doc_name = "Time_worked"
        )

rm(hours, lookup_table)
```


```{r, echo = F, message = F, warning = F}

hours_tab <- structured_hours %>% 
  group_by(week,activity) %>% 
  summarise(Hours = sum(minutes))  %>% # sum up minutes across days
  mutate(Hours = plyr::round_any(Hours, 15, ceiling)) %>%  
  # round raw minutes to nearest 15 min interval
  mutate(Hours = Hours/60) %>% # divide by 60 to create Hours
  mutate(activity = str_replace_all(activity, "_", " "))

knitr::kable(hours_tab, 
             align = "lcr", 
             col.names = c('Week', 'Activity', 'Hours'), 
             caption = "Hours Worked by Week and Activity", 
             booktabs = T)

hours_tab %>% 
  group_by(activity) %>% 
  summarize(Hours = sum(Hours)) %>% 
  knitr::kable( 
             align = "lc", 
             col.names = c('Activity', 'Hours'), 
             caption = "Total Hours Worked by Activity", 
             booktabs = T)
  
hours_tab %>% 
  group_by(week) %>% 
  summarize(Hours = sum(Hours)) %>% 
  knitr::kable( 
             align = "lc", 
             col.names = c('Week', 'Hours'), 
             caption = "Total Hours by Week ", 
             booktabs = T
             )

hours_tab1 <- hours_tab %>% 
  ungroup() %>% 
  group_by(week, activity) %>%  
  arrange(Date) %>% 
  summarize(Hours = sum(Hours)) %>%
  mutate(Hours = format(round(Hours, 2), nsmall = 2)) %>% 
  arrange(week)

write.csv(hours_tab1, 'hrs_academic_week_activity.csv')

rm(hours_tab, structured_hours, hours_tab1)
```



```{r Create Syllabus Table, echo = F, warning=F}

Date_table <- data.frame(
  'I' = c(1.04, 1.06, 1.07),
  'II' = c(1.11, 1.13, 1.14),
  'III' = c(1.18, 1.20, 1.21),
  'IV' = c(1.25, 1.27, 1.28),
  'V' = c(2.01, 2.03, 2.04),
  'VI' = c(2.08, 2.10, 2.11),
  'VII' = c(2.15, 2.17, 2.18),
  'VIII' = c(2.22, 2.24, 2.25),
  'IX' = c(3.01, 3.03, 3.04),
  'X' = c(3.08, 3.10, 3.11),
  'XI' = c(3.15, 3.17, NA)
) %>% 
  gather() %>% 
  rename(Week = key, Date = value)

Syllabus_table <- data.frame(
  'I' = c('Introduction to the course', 
                'Introduction to R', 
                'Intro Lab'
                ),
  'II' = c('R Data Structures',
                'Data Management I', 
                'Intro Lab II'
                ),
  'III' = c('Data Management III', 
                'Data Management II',
                'Data Management Lab'
                ),
  'IV' = c('Graphics I',
                'Graphics II',
                'Graphics Lab'
                ),
  'V' = c('Graphics III',
                'Downloading & Processing Data',
                'Download & Process Lab'
                ),
  'VI' = c('Project Proposal Developement', 
                'R Markdown',
                'Project Proposal Lab'),
  'VII' = c('Spatial Data I',
                'Spatial Data II',
                'Spatial Data Lab'
                ),
  'VIII' = c('Modeling I',
                'Modeling II', 
                'Modeling Lab'
                ),
  'IX' = c('Github',
                'Work on Project',
                'Github Lab'),
  'X' = c('Reading Week',
                'Reading Week', 
                'Reading Week'),
  'XI' = c('Project Presentations',
                'Project Presentations',
                NA)
) %>% 
  gather() %>% 
  rename(Week = key, Topic = value)

syllabus <- cbind(Date_table, Syllabus_table)
syllabus <- syllabus[,c(1:2,4)]

keep <- seq(from = 1, to = 33, by = 3)
'%notin%' <- Negate('%in%')
keep <- 1:33 %notin% keep
syllabus[c(keep),1] <- ""

syllabus %>% 
  knitr::kable( 
             align = "lll", 
             col.names = c('Week', 'Date', 'Topic'), 
             caption = "Syllabus", 
             booktabs = T
             )

rm(Date_table, Syllabus_table)
```

